language: csharp
rvm: 2.3
notifications:
  email: false
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
matrix:
  include:
    - os: linux
      dotnet: 2.1.300
      mono: none
      env: DOTNETCORE=1
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode9.1
      dotnet: 2.1.300
      mono: none
      env: DOTNETCORE=1
install:
  - dotnet restore
script:
  - mbsuild /p:Configuration=Release
