version: '1.13.{build}'
image: 
- Visual Studio 2017
- Ubuntu
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:  
       secure: 1Ce1wX4c2duHsRshiJRZFVIe6VI/r0WTAUG/tXuGFue9CmTI13NJRgZbl9irVKBA
  op_build_user: "Geo Perez"
  op_build_user_email: "geovanni.perez@gmail.com"
  access_token:
       secure: HzWdswNyfQbQ0vLk9IQyO+Ei9mxoPYp9rvv6HPhtC9J/Fm7EHRzyV953pbPRXI9I
before_build:
- dotnet restore --verbosity q
build_script:
- msbuild /p:Configuration=Release Unosquare.Labs.EmbedIO.sln
